# Generated by Django 4.0.3 on 2022-05-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_user_user_ip_alter_voting_user_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_ip',
            field=models.CharField(max_length=24),
        ),
    ]
