# Generated by Django 4.0.3 on 2022-05-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_alter_resulttype_description_alter_resulttype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulttype',
            name='image',
            field=models.ImageField(upload_to='static/firstapp/img/'),
        ),
    ]
