# Generated by Django 4.0.3 on 2022-05-21 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_alter_resulttype_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResultStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.resulttype')),
                ('user_ip', models.ForeignKey(default='0.0.0.0', on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.user')),
            ],
        ),
    ]
