# Generated by Django 4.0.3 on 2022-05-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_userresultstorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_point',
            field=models.BooleanField(default=True),
        ),
    ]
