# Generated by Django 4.0.3 on 2022-05-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_choice_choice_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='EI', max_length=10),
        ),
    ]
